routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

// Route::view('/', 'home')->name('home');
Route::view('/home', 'home')->name('home')->middleware('translate');

// Route::get('/', function () { return view('welcome'); });
Route::view('/', 'welcome')->name('welcome')->middleware('translate');

Route::view('/about', 'about')->name('about')->middleware('translate');
Route::view('/portfolio', 'portfolio')->name('portfolio')->middleware('translate');

Route::view('/contact', 'contact')->name('contact')->middleware('translate');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::view('/sidebar', 'sidebar')->name('sidebar')->middleware('translate');

// Route::get('/courses', [CourseController::class, 'index'])->name('courses.index');
// Route::get('/courses/create', [CourseController::class, 'create'])->name('courses.create');
// Route::post('/courses', [CourseController::class, 'store'])->name('courses.store');
// Route::get('/courses/edit/{course}', [CourseController::class, 'edit'])->name('courses.edit');
// Route::patch('/courses/update/{course}', [CourseController::class, 'update'])->name('courses.update');
// Route::delete('/courses/{course}', [CourseController::class, 'destroy'])->name('courses.destroy');
// // Route::get('/courses/{id}', [CourseController::class, 'show'])->name('courses.show');
// // Rutas Amigables -> poner al final
// Route::get('/courses/{course}', [CourseController::class, 'show'])->name('courses.show');

Route::resource('courses', CourseController::class)->middleware('translate');
// Route::resource('projects', CourseController::class)->names('courses')->parameters(['projects' => 'course']);

Route::resource('messages', MessageController::class)->middleware('auth')->middleware('translate');
Route::resource('users', UserController::class)->middleware('auth')->middleware('translate');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

// Evitar que el registro esté activo
// Auth::routes(['registrer' => false]);


//LANG
Route::get('/lang/{language}', function ($language) {
    Session::put('language',$language);
    return redirect()->back();
})->name('language');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/about.blade.php
@extends('layouts.app-primary')

@section('title', trans('Aboud'))

@section('breadcrumb')
<li class="breadcrumb-item" aria-current="page">
    <span class="d-inline-block icon-width oi oi-home"></span><a href="{{ url('/') }}">&nbsp;@lang('Home')</a>
</li>
<li class="breadcrumb-item active" aria-current="page"><a>@lang('About')</a></li>
@endsection

@section('content')

@include('layouts.proyects')
@include('layouts.filter-div')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/contact.blade.php
@extends('layouts.app-primary')

@section('title', trans('Contact'))

@section('breadcrumb')
<li class="breadcrumb-item" aria-current="page">
    <span class="d-inline-block icon-width oi oi-home"></span><a href="{{ url('/') }}">&nbsp;@lang('Home')</a>
</li>
<li class="breadcrumb-item active" aria-current="page"><a>@lang('Contact')</a></li>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-6 p-2">
            <div class="text-paradox border shadow rounded info-left">
                <div class="container p-5">
                    <h1 class="display-4 text-center">Formulario</h1>
                    <h1 class="display-4 text-center">de <span class="paradox">contacto</span></h1><br>
                    <p class="lead">Si necesitas cualquier tipo de información, contacta con nosotros y te ayudaremos en todo lo posible.</p>
                    <p class="lead">info@paradox-web.com</p>
                    <p class="lead">+34 697 32 19 44</p>
                </div>
            </div><br>
        </div>
        <div class="col-12 col-sm-12 col-lg-6 text-black p-2">
            {{-- <div class="shadow rounded" style="background-image:url('images/pages/stylized-height-topographic-map-contour-260nw-754709692.png');"> --}}
            <div class="border shadow rounded bg-white info-right">
                <div class="container p-4">
                    @if(session('status'))
                        {{ session('status') }}
                    @else
                        <br>
                        <form method="POST" action="/contact" >
                            @csrf
                            <div class="row">
                                <div class="col form-group">
                                    <label for="name">Nombre</label>
                                    <input class="form-control bg-light shadow-sm @error('name') is-invalid @else border-1 @enderror"
                                    name="name" placeholder="Nombre..." value="{{ old('name') }}">
                                    @error('name')
                                        <span class="invalid-feedback">
                                            <small>{{ $message }}</small>
                                        </span>
                                    @enderror
                                </div>
                                <div class="col form-group">
                                    <label for="email">Email</label>
                                    <input class="form-control bg-light shadow-sm @error('email') is-invalid @else border-1 @enderror"
                                    name="email" placeholder="Email..." value="{{ old('email') }}">
                                    @error('email')
                                        <span class="invalid-feedback">
                                            <small>{{ $message }}</small>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="subject">Asunto</label>
                                <input class="form-control bg-light shadow-sm @error('subject') is-invalid @else border-1 @enderror"
                                name="subject" placeholder="Asunto..." value="{{ old('subject') }}">
                                @error('subject')
                                    <span class="invalid-feedback">
                                        <small>{{ $message }}</small>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="content">Mensaje</label>
                                <textarea class="form-control bg-light shadow-sm @error('content') is-invalid @else border-1 @enderror"
                                name="content" id="" cols="30" rows="10">{{ old('content') }}</textarea>
                                @error('content')
                                    <span class="invalid-feedback">
                                        <small>{{ $message }}</small>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary border btn-block">@lang('Send')</button>
                            </div>

                        </form><br>
                    @endif
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-12 col-sm-12 col-lg-6 p-2">
            <div id="mapid" class="border shadow rounded info-left"></div>
        </div>
        <div class="col-12 col-sm-12 col-lg-6 p-2">
            <div class="text-paradox-2 border shadow rounded info-right" style="background-image:url('images/pages/geometrical-linear-pattern-260nw-621214532.png');">
                <div class="container"><br>
                    <a class="navbar-brand d-flex align-items-center">
                        <span class="pt-2 paradox">PARADOX WEB</span>
                    </a>
                    <hr style="margin-bottom:10px;">
                    <small>Nos preocupamos por tu negocio online y, por este motivo, encontraremos la mejor solución de hosting, desarrollaremos tu página web o aplicación online con las mejores garantías y, con nuestras técnicas de posicionamiento en los buscadores, te sorprenderás con los resultados.</small>
                    <br><hr style="margin-top:10px;"><br>
                    <div class="footer-pad">
                        <small>
                            <div class="row">
                                <div class="col">
                                    <address>
                                        <strong>PARADOX WEB</strong><br />
                                        <span class="oi oi-location"></span> Figueres, GI 17600<br />
                                        <abbr title="Phone"></abbr><span class="oi oi-phone"></span> +34 697321944<br>
                                        <span class="oi oi-envelope-closed"></span><a href="mailto:info@paradox-web.com"> info@paradox-web.com</a>
                                    </address>
                                </div>
                                <div class="col">
                                    <address>
                                        <strong>No disponemos de oficina fisica.</strong><br />
                                        <strong>Todos nuestros servicios son remotos.</strong><br />
                                        {{-- <a href="mailto:bertofern@gmail.com"><i class="fab fa-skype"></i> bertofern@gmail.com</a> --}}
                                        <i class="fab fa-skype fa-lg"></i>&nbsp;
                                        <i class="fas fa-video fa-lg"></i>
                                    </address>
                                </div>
                            </div>
                            <hr>
                            <a href="#">
                                <i class="fab fa-twitter fa-lg"></i>
                            </a>&nbsp;
                            <a href="#">
                                <i class="fab fa-facebook fa-lg"></i>
                            </a>&nbsp;
                            <a href="#">
                                <i class="fab fa-instagram fa-lg"></i>
                            </a>&nbsp;
                            <a href="#">
                                <i class="fab fa-linkedin fa-lg"></i>
                            </a>
                        </small>
                    </div><br>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.app-primary')

@section('title', 'Home')

@section('css-after')
    <style>
        .popover-header {
            color: black;
        }
        #alert {
            position: fixed;
            top: 0;
            right: 0;
            margin: 25px;
        }
    </style>
@endsection

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">
    <a><span class="d-inline-block icon-width oi oi-home"></span> @lang('Home')</a>
</li>
@endsection

@section('content')

<div id="alert" class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Wellcome</strong> You are in Home!
    <button id="popover-1" type="button" class="btn btn-sm btn-info badge badge-pill" data-bs-toggle="popover" title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?"><i class="fas fa-info"></i></button>
    <a href="services.html" class="alert-link">Entra ya!</a>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{{-- @include('layouts.mini-slider') --}}

@endsection


@section('js-after')
    <script>
        var popover = new bootstrap.Popover(document.querySelector('#popover-1'));
    </script>
@endsection

resources/views/navigation-dropdown.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-jet-application-mark class="block h-9 w-auto" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-jet-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-jet-dropdown align="right" width="48">
                    <x-slot name="trigger">

                        @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                            @if (empty(Auth::user()->profile_photo_path))
                                <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out">
                                    <img class="h-8 w-8 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                </button>
                            @else
                                <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                                    <div>{{ Auth::user()->name }}</div>
                                    <div class="ml-1">
                                        <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </div>
                                </button>
                            @endif
                        @else
                            <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                                <div>{{ Auth::user()->name }}</div>

                                <div class="ml-1">
                                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                            </button>
                        @endif
                    </x-slot>

                    <x-slot name="content">
                        <!-- Account Management -->
                        <div class="block px-4 py-2 text-xs text-gray-400">
                            {{ __('Manage Account') }}
                        </div>

                        <x-jet-dropdown-link href="{{ route('profile.show') }}">
                            {{ __('Profile') }}
                        </x-jet-dropdown-link>

                        @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                            <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                {{ __('API Tokens') }}
                            </x-jet-dropdown-link>
                        @endif

                        <div class="border-t border-gray-100"></div>

                        <!-- Team Management -->
                        @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Manage Team') }}
                            </div>

                            <!-- Team Settings -->
                            <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                {{ __('Team Settings') }}
                            </x-jet-dropdown-link>

                            @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                    {{ __('Create New Team') }}
                                </x-jet-dropdown-link>
                            @endcan

                            <div class="border-t border-gray-100"></div>

                            <!-- Team Switcher -->
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Switch Teams') }}
                            </div>

                            @foreach (Auth::user()->allTeams() as $team)
                                <x-jet-switchable-team :team="$team" />
                            @endforeach

                            <div class="border-t border-gray-100"></div>
                        @endif

                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-jet-dropdown-link href="{{ route('logout') }}"
                                                onclick="event.preventDefault();
                                                            this.closest('form').submit();">
                                {{ __('Logout') }}
                            </x-jet-dropdown-link>
                        </form>
                    </x-slot>
                </x-jet-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <img class="h-10 w-10 rounded-full" src="{{ asset('storage/' . Auth::user()->profile_photo_url) }}" alt="{{ Auth::user()->name }}" />
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                        {{ __('Logout') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                        {{ __('Create New Team') }}
                    </x-jet-responsive-nav-link>

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
    </div>
</nav>

resources/views/portfolio.blade.php
@extends('layouts.app-primary')

@section('title', trans('Portfolio'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection