routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

// Route::view('/', 'home')->name('home');
Route::view('/home', 'home')->name('home')->middleware('translate');

// Route::get('/', function () { return view('welcome'); });
Route::view('/', 'welcome')->name('welcome')->middleware('translate');

Route::view('/about', 'about')->name('about')->middleware('translate');
Route::view('/portfolio', 'portfolio')->name('portfolio')->middleware('translate');

Route::view('/contact', 'contact')->name('contact')->middleware('translate');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::view('/sidebar', 'sidebar')->name('sidebar')->middleware('translate');

// Route::get('/courses', [CourseController::class, 'index'])->name('courses.index');
// Route::get('/courses/create', [CourseController::class, 'create'])->name('courses.create');
// Route::post('/courses', [CourseController::class, 'store'])->name('courses.store');
// Route::get('/courses/edit/{course}', [CourseController::class, 'edit'])->name('courses.edit');
// Route::patch('/courses/update/{course}', [CourseController::class, 'update'])->name('courses.update');
// Route::delete('/courses/{course}', [CourseController::class, 'destroy'])->name('courses.destroy');
// // Route::get('/courses/{id}', [CourseController::class, 'show'])->name('courses.show');
// // Rutas Amigables -> poner al final
// Route::get('/courses/{course}', [CourseController::class, 'show'])->name('courses.show');

Route::resource('courses', CourseController::class)->middleware('translate');
// Route::resource('projects', CourseController::class)->names('courses')->parameters(['projects' => 'course']);

Route::resource('messages', MessageController::class)->middleware('auth')->middleware('translate');
Route::resource('users', UserController::class)->middleware('auth')->middleware('translate');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

// Evitar que el registro esté activo
// Auth::routes(['registrer' => false]);


//LANG
Route::get('/lang/{language}', function ($language) {
    Session::put('language',$language);
    return redirect()->back();
})->name('language');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;

use Laravelista\Comments\Commenter;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use Commenter;

    public function roles() {
        return $this->belongsToMany(Role::class, 'role_user');
    }

    public function hasRoles(array $roles) {
        foreach ($roles as $role) {
            foreach ($this->roles as $roleUser) {
                if ($roleUser->name === $role) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller {

    function __construct() {
        $this->middleware('auth');
        $this->middleware('roles:super-admin,admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('users.index', [
            // 'users' => User::orderby('created_at', 'ASC')->paginate(10)
            'users' => User::latest()->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //Proteccion contra la asignacion massiva
        $fields = request()->validate([
            'name'=> 'required',
            'email'=> 'required',
            'password'=> 'required',
        ]);
        User::create($fields);
        return redirect()->route('users.index')->with('status', 'El Usuario fue creado con éxito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user) {
        return view('users.show', [
            'user' => $user
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user) {
        return view('users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user) {
        $user->update($request->validated());
        return redirect()->route('users.show', $user)->with('status', 'El Usuario fue actualizado con éxito.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user) {
        $user->delete();
        return redirect()->route('users.index')->with('status', 'El Usuario fue eliminado con éxito.');
    }



    /* AJAX request */
    public function getUser(Request $request) {
        ## Read value
        $draw = $request->get('draw');
        $start = $request->get("start");
        $rowperpage = $request->get("length"); // Rows display per page

        $columnIndex_arr = $request->get('order');
        $columnName_arr = $request->get('columns');
        $order_arr = $request->get('order');
        $search_arr = $request->get('search');

        $columnIndex = $columnIndex_arr[0]['column']; // Column index
        $columnName = $columnName_arr[$columnIndex]['data']; // Column name
        $columnSortOrder = $order_arr[0]['dir']; // asc or desc
        $searchValue = $search_arr['value']; // Search value

        // Total records
        $totalRecords = User::select('count(*) as allcount')->count();
        $totalRecordswithFilter = User::select('count(*) as allcount')->where('name', 'like', '%' .$searchValue . '%')->count();

        // Fetch records
        $records = User::orderBy($columnName,$columnSortOrder)
        ->where('employees.name', 'like', '%' .$searchValue . '%')
        ->select('employees.*')
        ->skip($start)
        ->take($rowperpage)
        ->get();

        $data_arr = array();

        foreach($records as $record) {
            $id = $record->id;
            $username = $record->username;
            $name = $record->name;
            $email = $record->email;

            $data_arr[] = array(
                "id" => $id,
                "username" => $username,
                "name" => $name,
                "email" => $email
            );
        }

        $response = array(
        "draw" => intval($draw),
        "iTotalRecords" => $totalRecords,
        "iTotalDisplayRecords" => $totalRecordswithFilter,
        "aaData" => $data_arr
        );

        echo json_encode($response);
        exit;
    }
}

resources/views/users/create.blade.php
@extends('layouts.app-primary')

@section('title', trans('Users - Create'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-12">@Lang('Create Course')</div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('courses.store') }}" >
                        <div class="form-row">
                            <div class="form-group col-md-6" style="border-right:2px solid grey;">
                                @csrf
                                <div class="form-group form-row mr-2">
                                    <label for="title" class="col-12">
                                        Title of course<br>
                                        <input name="title" class="form-control" placeholder="Title of course" value="{{ old('title') }}">
                                    </label>
                                    @error('title')
                                        {{-- <div class="alert alert-danger">{{ $message }}</div> --}}
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>

                                <div class="form-group form-row mr-2">
                                    <label for="slug" class="col-12">
                                        URL of course<br>
                                        <input name="slug" class="form-control" placeholder="URL of course" value="{{ old('slug') }}">
                                    </label>
                                    @error('slug')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group col-md-6">
                                <div class="form-group form-row ml-2">
                                    <label for="description" class="col-12">
                                        Description of course<br>
                                        <textarea name="description" class="form-control" rows="10">{{ old('description') }}</textarea>
                                    </label>
                                    @error('description')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>
                        </div>




                        <button class="btn btn-secondary btn-sm btn-block">@lang('Send')</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app-primary')

@section('title', trans('Users - Edit'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-6">@Lang('Edit User')</div>
                        <div class="col-6 text-right">
                            <div class="btn-group-vertical">
                                <span class="badge badge-info" style="width:100%;">Back</span>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a class="btn btn-light btn-outline-secondary btn-sm" href="/users/create">
                                        <i class="fas fa-chevron-left"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('users.update', $user) }}" >
                        <div class="form-row">
                            <div class="form-group col-md-6" style="border-right:2px solid grey;">
                                @csrf
                                @method('PATCH')
                                {{-- <input type="hidden" name="_method" value="PATCH"> --}}
                                <div class="form-group form-row mr-2">
                                    <label for="title" class="col-12">
                                        Title of user<br>
                                        <input name="title" class="form-control" placeholder="Title of user" value="{{ old('title', $user->title) }}">
                                    </label>
                                    @error('title')
                                        {{-- <div class="alert alert-danger">{{ $message }}</div> --}}
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>

                                <div class="form-group form-row mr-2">
                                    <label for="slug" class="col-12">
                                        URL of user<br>
                                        <input name="slug" class="form-control" placeholder="URL of user" value="{{ old('slug', $user->slug) }}">
                                    </label>
                                    @error('slug')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group col-md-6">
                                <div class="form-group form-row ml-2">
                                    <label for="description" class="col-12">
                                        Description of user<br>
                                        <textarea name="description" class="form-control" rows="10">{{ old('description', $user->description) }}</textarea>
                                    </label>
                                    @error('description')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>
                        </div>




                        <button class="btn btn-secondary btn-sm btn-block">@lang('Update')</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app-primary')

@section('title', trans('Users'))

@section('content')

{{-- <div class="table-responsive"> --}}
<div class="container">
    <table id="table-users" class="table table-striped table-bordered table-sm table-condensed">
        <thead class="thead-light">
            <tr>
                <th scope="col" width="10%"></th>
                <th scope="col" width="20%">User</th>
                <th scope="col" width="20%">Email</th>
                <th scope="col" width="10%">Role</th>
                <th scope="col">Verified</th>
                <th scope="col">Status</th>
                <th scope="col">Last Connection</th>
                <th scope="col" width="1%">Created</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($users as $user)
            {{-- <a href="{{ route('users.show', $user) }}"></a> --}}
            <tr class="table-row" data-href="{{ route('users.show', $user) }}">
                {{-- <td><input type="checkbox" id="msn{{ $user->id }}" name="msn{{ $user->id }}" value="msn{{ $user->id }}"></td>} --}}
                <td class="text-center align-middle">
                    @if (!empty($user->profile_photo_path))
                        <img class="rounded mx-auto d-block" src="{{ asset('storage/' . $user->profile_photo_path)}}" style="width:50px;height:auto;" alt="Profile Image">
                    @else
                        <i class="fas fa-user fa-2x"></i>
                    @endif
                </td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    @foreach ($user->roles as $role)
                        <span class="badge rounded-pill bg-secondary">{{ $role->name }}</span>
                    @endforeach
                </td>
                <td>{{ $user->email_verified_at }}</td>
                <td>
                    @if(Cache::has('user-is-online-' . $user->id))
                        <span class="badge bg-success">Online</span>
                    @else
                        <span class="badge bg-danger">Offline</span>
                    @endif
                </td>
                <td>
                    @if($user->last_conection != null)
                        {{-- {{ $user->last_conection }} --}}
                        {{ \Carbon\Carbon::parse($user->last_conection)->diffForHumans() }}
                    @else
                        <span class="">Never</span>
                    @endif
                </td>
                {{-- <td>
                    @if($user->created_at->format('d/m/Y') == date("d/m/Y"))
                    {{ $user->created_at->format('h:i') }}&nbsp
                    @else
                    {{ $user->created_at->format('d M') }}&nbsp
                    @endif
                </td> --}}
                <td>
                    <div class="btn-group-vertical">
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a class="btn btn-primary btn-sm" href="{{ route('users.edit', $user) }}">
                                <i class="fas fa-pencil-alt"></i>
                            </a>
                            <a class="btn btn-danger btn-sm" href="#" onclick="document.getElementById('delete-user-form')">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>

                    <form id="delete-user-form" method="POST" action="{{ route('users.destroy', $user) }}" >
                        @csrf
                        @method('DELETE')
                    </form>

                </td>
            </tr>
            @empty
            <p>No hay usuarios para mostrar</p>
            @endforelse
        </tbody>
    </table>
    {{-- <div class="pagination justify-content-center">
        {{ $users->links() }}
    </div> --}}
    {{-- <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {{ $users->links() }}
        </ul>
    </nav> --}}
</div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app-primary')

@section('title', trans('Users | ') . $user->name)

@section('css-after')
<style>
    .btn-users {
        color: white;
    }
</style>
@endsection

@section('content')
<div class="container">
    <nav class="navbar navbar-expand-lg d-flex justify-content-between pl-0">
        <div class="btn-group ml-2">
            <a class="btn btn-outline-light" href="{{ route('users.index') }}">
                <i class="fas fa-chevron-left"></i>
            </a>
        </div>
        <div class="text-center">
            <p class="">{{ $user->name }}</p>
        </div>
        <div>
            <button class="btn btn-group btn-sm btn-outline-dark mr-2">
                <i class="fas fa-pen"></i>
            </button>
            <button class="btn btn-group btn-sm btn-outline-light mr-2">
                <i class="fas fa-file-alt"></i>
            </button>
            <div class="btn-group" role="group">
                <button class="btn btn-sm btn-outline-light mr-2">
                    <i class="fas fa-file-alt"></i>
                </button>
            </div>
            <div class="btn-group" role="group">
                <form method="POST" action="{{ route('users.destroy', $user) }}" >
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-sm btn-outline-light mr-2">
                        <i class="fas fa-trash"></i>
                    </button>
                </form>
            </div>
            {{-- <button class="btn-group mr-2 btn-users">
                <i class="fas fa-file-alt"></i>
            </button>
            <div class="btn-group mr-2" role="group">
                <form method="POST" action="{{ route('users.destroy', $user) }}" >
                    @csrf
                    @method('DELETE')
                    <button class="btn-users">
                        <i class="fas fa-trash"></i>
                    </button>
                </form>
            </div> --}}
        </div>
    </nav><br>
    <div class="row">
        <div class="col-3">
            <div class="card shadow">
                <div style="position: relative; ">
                    <div style="position:absolute;background-color:rgb(31, 46, 95);width:100%;height:50px">&nbsp;</div>
                    <div style="position:absolute;top:30px;left:0;right:0;margin: auto;">
                        <div class="text-center">
                            @if (!empty($user->profile_photo_path))
                                <img class="rounded mx-auto d-block" src="{{ asset('storage/' . $user->profile_photo_path)}}" style="width:100px;height:100px;" alt="Profile Image">
                            @else
                                <i class="fas fa-user fa-4x" style="width:100px;height:100px;"></i>
                            @endif
                            <p class="card-text">{{ $user->name }}</p>
                            <p class="card-text">{{ $user->email }}</p>
                            <small class="text-muted">Programmer - Web Developer (Junior), in Interactiva Online.</small>
                        </div>
                    </div>
                </div>
                {{-- <div class="card-header bg-white text-center">
                    <div style="position: relative;">
                        <div style="position:absolute;background-color:rgb(220, 124, 21, 0.5);width:100%;height:50px">&nbsp;</div>
                        <div style="position:absolute;top:30px;left:0;right:0;margin: auto;">
                            <img class="rounded mx-auto d-block" src="{{asset('storage/' . $user->profile_photo_path)}}" style="width:100px;height:100px;" alt="Profile Image">
                        </div>
                    </div><br><br>
                    <div class="" style="background-color:rgb(220, 124, 21, 0.5);width:100%;height:80px">&nbsp;</div>
                    <img class="rounded mx-auto d-block" src="{{asset('storage/' . $user->profile_photo_path)}}" style="width:100px;height:100px;" alt="Profile Image">
                    <p class="card-text">{{ $user->name }}</p>
                    <p class="card-text">{{ $user->email }}</p>
                    <small class="text-muted">Programmer - Web Developer (Junior), in Interactiva Online.</small>
                </div> --}}
                <div class="card-body" style="margin-top: 250px;">

                    <p class="card-text"><small class="text-muted">Created {{ $user->created_at->diffForHumans() }}</small></p>
                </div>
                <div class="card-footer bg-white">
                    <p class="card-text"><small class="text-muted"><i class="far fa-calendar-alt"></i>&nbsp&nbsp Created {{ $user->created_at->diffForHumans() }}</small></p>
                </div>
                <div class="card-footer text-center bg-white">
                    <a class="btn badge text-white" style="background-color:#dc7c15"><i class="fas fa-paper-plane"></i>&nbsp&nbsp Send Message</a>
                </div>
            </div>
        </div>
        <div class="col-9">
            <div class="card shadow">
                <div class="card-body">
                    <img class="mx-auto d-block" src="{{asset('images/default_10x1.png')}}" alt="Card image cap">
                    <br><hr><br>
                    <p class="card-text">Inglés - Intermediate II </p>
                    <p class="card-text">Estatus: Inscrito</p>
                    <p class="card-text">Descripcion: Id expedita hic officia rem recusandae modi. Quis omnis vel quisquam dolorem qui aut ea suscipit. Ut atque doloremque ducimus. Iusto quasi optio nulla voluptatibus velit sapiente.</p>
                    <p class="card-text"><small class="text-muted">Created {{ $user->created_at->diffForHumans() }}</small></p>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection