routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

// Route::view('/', 'home')->name('home');
Route::view('/home', 'home')->name('home')->middleware('translate');

// Route::get('/', function () { return view('welcome'); });
Route::view('/', 'welcome')->name('welcome')->middleware('translate');

Route::view('/about', 'about')->name('about')->middleware('translate');
Route::view('/portfolio', 'portfolio')->name('portfolio')->middleware('translate');

Route::view('/contact', 'contact')->name('contact')->middleware('translate');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::view('/sidebar', 'sidebar')->name('sidebar')->middleware('translate');

// Route::get('/courses', [CourseController::class, 'index'])->name('courses.index');
// Route::get('/courses/create', [CourseController::class, 'create'])->name('courses.create');
// Route::post('/courses', [CourseController::class, 'store'])->name('courses.store');
// Route::get('/courses/edit/{course}', [CourseController::class, 'edit'])->name('courses.edit');
// Route::patch('/courses/update/{course}', [CourseController::class, 'update'])->name('courses.update');
// Route::delete('/courses/{course}', [CourseController::class, 'destroy'])->name('courses.destroy');
// // Route::get('/courses/{id}', [CourseController::class, 'show'])->name('courses.show');
// // Rutas Amigables -> poner al final
// Route::get('/courses/{course}', [CourseController::class, 'show'])->name('courses.show');

Route::resource('courses', CourseController::class)->middleware('translate');
// Route::resource('projects', CourseController::class)->names('courses')->parameters(['projects' => 'course']);

Route::resource('messages', MessageController::class)->middleware('auth')->middleware('translate');
Route::resource('users', UserController::class)->middleware('auth')->middleware('translate');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

// Evitar que el registro esté activo
// Auth::routes(['registrer' => false]);


//LANG
Route::get('/lang/{language}', function ($language) {
    Session::put('language',$language);
    return redirect()->back();
})->name('language');

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    use HasFactory;

    protected $fillable = [
        'subject', 'message',
    ];

    protected $guarded = [
        'id',
        'readed',
        'created_at',
        'updated_at',
    ];
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MessageController extends Controller
{

    // public function __construct()
    // {
    //     // $this->middleware('auth')->only('create', 'store', 'edit', 'update', 'destroy');
    //     $this->middleware('auth')->except('index', 'show');
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Sidebar info
        $totalMessages = Message::where('from_user_id', auth()->user()->id)->orWhere('to_user_id', auth()->user()->id)->count();
        $totalMessagesRecived = Message::where('to_user_id', auth()->user()->id)->count();
        $totalMessagesSended = Message::where('from_user_id', auth()->user()->id)->count();
        $totalMessagesNoReaded = Message::where('readed', false)->where('to_user_id', auth()->user()->id)->count();
        return view('messages.index', [
            'allMessages' => Message::where('from_user_id', auth()->user()->id)->orWhere('to_user_id', auth()->user()->id)->orderby('created_at', 'DESC')->paginate(10),

            // 1 -> Da problemas = Object of class stdClass could not be converted to string
            // 'allMessages' => DB::select(DB::raw('SELECT t2.conversations, t1.* FROM messages t1
            // JOIN (SELECT conversation_id, MAX(id) id, COUNT(conversation_id) as conversations FROM messages GROUP BY conversation_id) t2
            // ON t1.id = t2.id AND t1.conversation_id = t2.conversation_id;') ),

            // 2 -> No da problemas pero no se ve nada
            // 'allMessages' => Message::select(DB::raw("SELECT t2.conversations, t1.* FROM messages as t1
            // JOIN (SELECT conversation_id, MAX(id) as id, COUNT(conversation_id) as conversations FROM messages GROUP BY conversation_id) as t2
            // ON t1.id = t2.id AND t1.conversation_id = t2.conversation_id")),

            // 3 -> Da problemas
            // 'allMessages' => DB::table('messages as t1')->select('t2.conversations AS conversations, t1.*')
            // ->join('(SELECT conversation_id, MAX(id) id, COUNT(conversation_id) as conversations FROM messages GROUP BY conversation_id) as t2', function ($join) {
            //     $join->on('t1.id', '=', 't2.id')->on('t1.conversation_id', '=', 't2.conversation_id');
            // }),

            // $bit_ids = Bid::select(DB::raw('max(id) as id'))
            // ->where('buyer_account_ID', $request->id)
            // ->groupBy('seller_account_ID')
            // ->get(),

            // Corect Query
            // SELECT t1.*, t2.conversations FROM messages t1
            // JOIN (SELECT conversation_id, MAX(id) id, COUNT(conversation_id) conversations FROM messages GROUP BY conversation_id) t2
            // ON t1.id = t2.id AND t1.conversation_id = t2.conversation_id;

            'noReadedMessages' => Message::where('to_user_id', auth()->user()->id)->where('readed', false)->orderby('created_at', 'DESC')->paginate(10),
            'sendedMessages' => Message::where('from_user_id', auth()->user()->id)->orderby('created_at', 'DESC')->paginate(10),
            'recivedMessages' => Message::where('to_user_id', auth()->user()->id)->orderby('created_at', 'DESC')->paginate(10),
            // Sidebar info
            'totalMessages' => $totalMessages,
            'totalMessagesRecived' => $totalMessagesRecived,
            'totalMessagesSended' => $totalMessagesSended,
            'totalMessagesNoReaded' => $totalMessagesNoReaded
        ]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function show(Message $message) {
        if($message->readed == false) {
            $message->readed = true;
            $message->save();
        }

        $from_user = User::find($message->from_user_id);
        $to_user = User::find($message->to_user_id);

        // Sidebar info
        $totalMessages = Message::where('from_user_id', auth()->user()->id)->orWhere('to_user_id', auth()->user()->id)->count();
        $totalMessagesRecived = Message::where('to_user_id', auth()->user()->id)->count();
        $totalMessagesSended = Message::where('from_user_id', auth()->user()->id)->count();
        $totalMessagesNoReaded = Message::where('readed', false)->where('to_user_id', auth()->user()->id)->count();

        return view('messages.show', [
            'message' => $message,
            'from_user' => $from_user,
            'to_user' => $to_user,
            // Sidebar info
            'totalMessages' => $totalMessages,
            'totalMessagesRecived' => $totalMessagesRecived,
            'totalMessagesSended' => $totalMessagesSended,
            'totalMessagesNoReaded' => $totalMessagesNoReaded
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function edit(Message $message)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        $message->delete();
        return redirect()->route('messages.index')->with('status', 'El mensaje fue eliminado con éxito.');
    }

    public function destroyMore(Request $request) {
        $messages = $request->input('messages');
        foreach ($messages as $message => $id) {
            // $message= Message::find($id);
            $message = Message::findOrFail($id);
            $message->delete();
        }
        return back()->with('status','Operation Successful! You are destroy ' + count($messages) + ' messages');
     }


}

resources/views/messages/create.blade.php
@extends('layouts.app-primary')

@section('title', trans('Messages - Create'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-12">@Lang('Create Course')</div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('courses.store') }}" >
                        <div class="form-row">
                            <div class="form-group col-md-6" style="border-right:2px solid grey;">
                                @csrf
                                <div class="form-group form-row mr-2">
                                    <label for="title" class="col-12">
                                        Title of course<br>
                                        <input name="title" class="form-control" placeholder="Title of course" value="{{ old('title') }}">
                                    </label>
                                    @error('title')
                                        {{-- <div class="alert alert-danger">{{ $message }}</div> --}}
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>

                                <div class="form-group form-row mr-2">
                                    <label for="slug" class="col-12">
                                        URL of course<br>
                                        <input name="slug" class="form-control" placeholder="URL of course" value="{{ old('slug') }}">
                                    </label>
                                    @error('slug')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group col-md-6">
                                <div class="form-group form-row ml-2">
                                    <label for="description" class="col-12">
                                        Description of course<br>
                                        <textarea name="description" class="form-control" rows="10">{{ old('description') }}</textarea>
                                    </label>
                                    @error('description')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>
                        </div>




                        <button class="btn btn-secondary btn-sm btn-block">@lang('Send')</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/messages/edit.blade.php
@extends('layouts.app-primary')

@section('title', trans('Messages - Edit'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-6">@Lang('Edit Course')</div>
                        <div class="col-6 text-right">
                            <div class="btn-group-vertical">
                                <span class="badge badge-info" style="width:100%;">Back</span>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a class="btn btn-light btn-outline-secondary btn-sm" href="/courses/create">
                                        <i class="fas fa-chevron-left"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('courses.update', $course) }}" >
                        <div class="form-row">
                            <div class="form-group col-md-6" style="border-right:2px solid grey;">
                                @csrf
                                @method('PATCH')
                                {{-- <input type="hidden" name="_method" value="PATCH"> --}}
                                <div class="form-group form-row mr-2">
                                    <label for="title" class="col-12">
                                        Title of course<br>
                                        <input name="title" class="form-control" placeholder="Title of course" value="{{ old('title', $course->title) }}">
                                    </label>
                                    @error('title')
                                        {{-- <div class="alert alert-danger">{{ $message }}</div> --}}
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>

                                <div class="form-group form-row mr-2">
                                    <label for="slug" class="col-12">
                                        URL of course<br>
                                        <input name="slug" class="form-control" placeholder="URL of course" value="{{ old('slug', $course->slug) }}">
                                    </label>
                                    @error('slug')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group col-md-6">
                                <div class="form-group form-row ml-2">
                                    <label for="description" class="col-12">
                                        Description of course<br>
                                        <textarea name="description" class="form-control" rows="10">{{ old('description', $course->description) }}</textarea>
                                    </label>
                                    @error('description')
                                        <small>{{ $message }}</small><br>
                                    @enderror
                                </div>
                            </div>
                        </div>




                        <button class="btn btn-secondary btn-sm btn-block">@lang('Update')</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/messages/index.blade.php
@extends('layouts.messenger')

@section('title', trans('Messages'))

@section('content')

{{-- <div class="container">
    <div class="row align-items-center">
        <div class="col-6 font-weight-bold">@Lang('There are') {{ $totalMessages }} @Lang('messages - '){{
            $totalMessagesNoReaded }} @Lang(' no leidos')</div>
        <div class="col-6 text-right">
            <div class="btn-group-vertical">
                <span class="badge badge-info" style="width:100%;">New</span>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a class="btn btn-light btn-outline-secondary btn-sm" href="/messages/create">
                        <i class="fas fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div> --}}


{{-- All messages --}}
<div class="table-responsive show" id="all-messages">
    <table class="table table-sm table-condensed">
        <thead class="thead-light">
            <tr>
                <th scope="col" width="1%"></th>
                <th scope="col" width="20%">User</th>
                <th scope="col" width="20%">Subject</th>
                <th scope="col">Message</th>
                <th scope="col" width="20%" class="text-right"></th>
            </tr>
        </thead>
        <tbody>
            @forelse ($allMessages as $message)
            {{-- <a href="{{ route('messages.show', $message) }}"></a> --}}
            <tr class="table-row" data-href="{{ route('messages.show', $message) }}">
                <td><input type="checkbox" id="msn{{ $message->id }}" name="msn{{ $message->id }}"
                        value="msn{{ $message->id }}"></td>
                <td @if(!$message->readed && $message->to_user_id == auth()->user()->id)class="font-weight-bold" @endif>{{ $message->from_user_name }}</td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->subject }}</div>
                </td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->message }}</div>
                </td>
                <td class="text-right @if(!$message->readed && $message->to_user_id == auth()->user()->id)font-weight-bold @endif">
                    @if($message->created_at->format('d/m/Y') == date("d/m/Y"))
                    {{ $message->created_at->format('h:i') }}&nbsp
                    @else
                    {{ $message->created_at->format('d M') }}&nbsp
                    @endif
                </td>
            </tr>
            @empty
            <p>No hay mensajes para mostrar</p>
            @endforelse
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {{-- {{ $allMessages->links() }} --}}
        </ul>
    </nav>
</div>


{{-- No-readed-messages --}}
<div class="table-responsive d-none" id="no-readed-messages">
    <table class="table table-sm table-condensed">
        <thead class="thead-light">
            <tr>
                <th scope="col" width="1%"></th>
                <th scope="col" width="20%">User</th>
                <th scope="col" width="20%">Subject</th>
                <th scope="col">Message</th>
                <th scope="col" width="20%" class="text-right"></th>
            </tr>
        </thead>
        <tbody>
            @forelse ($noReadedMessages as $message)
            {{-- <a href="{{ route('messages.show', $message) }}"></a> --}}
            <tr class="table-row" data-href="{{ route('messages.show', $message) }}">
                <td><input type="checkbox" id="msn{{ $message->id }}" name="msn{{ $message->id }}"
                        value="msn{{ $message->id }}"></td>
                <td @if(!$message->readed && $message->to_user_id == auth()->user()->id)class="font-weight-bold" @endif>{{ $message->from_user_name }}</td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->subject }}</div>
                </td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->message }}</div>
                </td>
                <td class="text-right @if(!$message->readed && $message->to_user_id == auth()->user()->id)font-weight-bold @endif">
                    @if($message->created_at->format('d/m/Y') == date("d/m/Y"))
                    {{ $message->created_at->format('h:i') }}&nbsp
                    @else
                    {{ $message->created_at->format('d M') }}&nbsp
                    @endif
                </td>
            </tr>
            @empty
            <p>No hay mensajes para mostrar</p>
            @endforelse
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {{ $noReadedMessages->links() }}
        </ul>
    </nav>
</div>

{{-- Sended-messages --}}
<div class="table-responsive d-none" id="sended-messages">
    <table class="table table-sm table-condensed">
        <thead class="thead-light">
            <tr>
                <th scope="col" width="1%"></th>
                <th scope="col" width="20%">User</th>
                <th scope="col" width="20%">Subject</th>
                <th scope="col">Message</th>
                <th scope="col" width="20%" class="text-right"></th>
            </tr>
        </thead>
        <tbody>
            @forelse ($sendedMessages as $message)
            {{-- <a href="{{ route('messages.show', $message) }}"></a> --}}
            <tr class="table-row" data-href="{{ route('messages.show', $message) }}">
                <td><input type="checkbox" id="msn{{ $message->id }}" name="msn{{ $message->id }}"
                        value="msn{{ $message->id }}"></td>
                <td @if(!$message->readed && $message->to_user_id == auth()->user()->id)class="font-weight-bold" @endif>{{ $message->from_user_name }}</td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->subject }}</div>
                </td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->message }}</div>
                </td>
                <td class="text-right @if(!$message->readed && $message->to_user_id == auth()->user()->id)font-weight-bold @endif">
                    @if($message->created_at->format('d/m/Y') == date("d/m/Y"))
                    {{ $message->created_at->format('h:i') }}&nbsp
                    @else
                    {{ $message->created_at->format('d M') }}&nbsp
                    @endif
                </td>
            </tr>
            @empty
            <p>No hay mensajes para mostrar</p>
            @endforelse
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {{ $sendedMessages->links() }}
        </ul>
    </nav>
</div>

{{-- Recived-messages --}}
<div class="table-responsive d-none" id="recived-messages">
    <table class="table table-sm table-condensed">
        <thead class="thead-light">
            <tr>
                <th scope="col" width="1%"></th>
                <th scope="col" width="20%">User</th>
                <th scope="col" width="20%">Subject</th>
                <th scope="col">Message</th>
                <th scope="col" width="20%" class="text-right"></th>
            </tr>
        </thead>
        <tbody>
            @forelse ($recivedMessages as $message)
            {{-- <a href="{{ route('messages.show', $message) }}"></a> --}}
            <tr class="table-row" data-href="{{ route('messages.show', $message) }}">
                <td><input type="checkbox" id="msn{{ $message->id }}" name="msn{{ $message->id }}"
                        value="msn{{ $message->id }}"></td>
                <td @if(!$message->readed && $message->to_user_id == auth()->user()->id)class="font-weight-bold" @endif>{{ $message->from_user_name }}</td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->subject }}</div>
                </td>
                <td class="truncate-content @if(!$message->readed && $message->to_user_id == auth()->user()->id) font-weight-bold @endif">
                    <div class="truncate-text">{{ $message->message }}</div>
                </td>
                <td class="text-right @if(!$message->readed && $message->to_user_id == auth()->user()->id)font-weight-bold @endif">
                    @if($message->created_at->format('d/m/Y') == date("d/m/Y"))
                    {{ $message->created_at->format('h:i') }}&nbsp
                    @else
                    {{ $message->created_at->format('d M') }}&nbsp
                    @endif
                </td>
            </tr>
            @empty
            <p>No hay mensajes para mostrar</p>
            @endforelse
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {{ $recivedMessages->links() }}
        </ul>
    </nav>
</div>

@endsection

resources/views/messages/show.blade.php
@extends('layouts.messenger')

@section('title', trans('Messages | ' . $message->subject))

@section('content')

<div class="container pl-4">
    <nav class="navbar navbar-expand-lg navbar-light d-flex justify-content-between pl-0">
        <div>
            <a class="btn btn-light btn-outline-secondary btn-group" href="{{ route('messages.index') }}">
                <i class="fas fa-chevron-left"></i>
            </a>
            <h4 class="navbar-brand font-weight-bold btn-group">&nbsp&nbsp{{ $message->subject }}</h4>
        </div>

        <div>
            <span class="btn-group"><i class="fas fa-print"></i></span>
            <div class="btn-group" role="group" aria-label="Basic example">
                <form method="POST" action="{{ route('messages.destroy', $message) }}" >
                    @csrf
                    @method('DELETE')
                    <button class="btn ">
                        <i class="fas fa-trash"></i>
                    </button>
                </form>
            </div>
        </div>

    </nav>

    <div class="card shadow">
        <div class="card-header">
            <div class="media d-flex justify-content-between">
                @if ($from_user->profile_photo_path)
                    <img class="align-self-center mr-3" width="60"
                    src="{{asset('storage/' . $from_user->profile_photo_path)}}" alt="Profile Image">
                @else
                    <img class="align-self-center mr-3" width="60"
                        src="{{asset('images/default_4x4.png')}}" alt="Profile Image">
                @endif
                <div class="media-body">
                    <strong class="mt-0">{{ $from_user->name }}</strong><br>
                    <small class="mt-0">para {{ $to_user->name }}</small><br>
                </div>
                <small class="text-muted mr-4">{{ $message->created_at->diffForHumans() }}</small>
            </div>
        </div>
        <div class="card-body">
            <p class="card-text">{{ $message->message }}</p>
        </div>
    </div><br>

    <div class="card shadow">
        <div class="card-header bg-white">
            <div class="media d-flex justify-content-between">
                @if ($to_user->profile_photo_path)
                    <img class="align-self-center mr-3" width="60"
                    src="{{asset('storage/' . $to_user->profile_photo_path)}}" alt="Profile Image">
                @else
                    <img class="align-self-center mr-3" width="60"
                        src="{{asset('images/default_4x4.png')}}" alt="Profile Image">
                @endif
                <div class="media-body">
                    <small class="mt-0">para {{ $to_user->name }}</small><br>
                </div>
                <small class="text-muted mr-4">{{ $message->created_at->diffForHumans() }}</small>
            </div>
        </div>
        <form>
            <div class="card-body">
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="card-footer bg-white">
                <button class="btn btn-dark">Reply</button>
            </div>
        </form>
    </div>


</div>


@endsection