routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

// Route::view('/', 'home')->name('home');
Route::view('/home', 'home')->name('home')->middleware('translate');

// Route::get('/', function () { return view('welcome'); });
Route::view('/', 'welcome')->name('welcome')->middleware('translate');

Route::view('/about', 'about')->name('about')->middleware('translate');
Route::view('/portfolio', 'portfolio')->name('portfolio')->middleware('translate');

Route::view('/contact', 'contact')->name('contact')->middleware('translate');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::view('/sidebar', 'sidebar')->name('sidebar')->middleware('translate');

// Route::get('/courses', [CourseController::class, 'index'])->name('courses.index');
// Route::get('/courses/create', [CourseController::class, 'create'])->name('courses.create');
// Route::post('/courses', [CourseController::class, 'store'])->name('courses.store');
// Route::get('/courses/edit/{course}', [CourseController::class, 'edit'])->name('courses.edit');
// Route::patch('/courses/update/{course}', [CourseController::class, 'update'])->name('courses.update');
// Route::delete('/courses/{course}', [CourseController::class, 'destroy'])->name('courses.destroy');
// // Route::get('/courses/{id}', [CourseController::class, 'show'])->name('courses.show');
// // Rutas Amigables -> poner al final
// Route::get('/courses/{course}', [CourseController::class, 'show'])->name('courses.show');

Route::resource('courses', CourseController::class)->middleware('translate');
// Route::resource('projects', CourseController::class)->names('courses')->parameters(['projects' => 'course']);

Route::resource('messages', MessageController::class)->middleware('auth')->middleware('translate');
Route::resource('users', UserController::class)->middleware('auth')->middleware('translate');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

// Evitar que el registro esté activo
// Auth::routes(['registrer' => false]);


//LANG
Route::get('/lang/{language}', function ($language) {
    Session::put('language',$language);
    return redirect()->back();
})->name('language');

resources/views/layouts/app-secondary.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }} - @yield('title', 'home')</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Open Iconic -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-foundation.min.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- Bootstrap core CSS -->
    {{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet"> --}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {{-- <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet"> --}}
    <!-- MDB -->
    {{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.0.0/mdb.min.css" rel="stylesheet" /> --}}
    <!-- Bootstrap Datatables -->
    {{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet"> --}}

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Leafletjs.com -->
    <link rel='stylesheet' href='https://unpkg.com/leaflet@1.7.1/dist/leaflet.css' integrity='sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==' crossorigin=''>

    <!-- Icon-Flag -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css" integrity="sha512-Cv93isQdFwaKBV+Z4X8kaVBYWHST58Xb/jVOcV9aRsGSArZsgAnFIhMpDoMDcFNoUtday1hdjn0nGp3+KZyyFw==" crossorigin="anonymous" />

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <style>
        /* Fonts */
        @font-face { font-family: myRufan; src: url(../fonts/Rutan/rutan-demibold.otf); }
        .paradox { font-family: myRufan; }
        body {
            width: 100%;
            /* background: #000000; */
            /* color: white; */
            background-repeat: repeat;
            background-image:url('images/pages/organic-line-seamless-pattern-irregular-260nw-1880231914.png');
            background-size: 10%;
        }
    </style>

    @yield('css-after')

</head>
<body>
    <div id="app">
        @include('layouts.nav')
        @if (auth()->check())
            @if (auth()->user()->hasRoles(['super-admin','admin']))
                @include('layouts.nav-admin')
            @endif
        @endif

        @include('layouts.jumbotron')
        @include('layouts.breadcrumb')

        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('status') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        <main class="py-4">
            @yield('content')
        </main>

        @include('layouts.footer')
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- MDB -->
    {{-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.0.0/mdb.min.js"></script> --}}
    <!-- Bootstrap Datatables -->
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>

    <!-- leafletjs -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script src='{{ asset('js/leafletjs.js') }}' type="text/javascript"></script>

    <!-- Efects scroll -->
    <script src="https://unpkg.com/scrollreveal"></script>
    <!-- Efects scroll & Scroll to top-->
    <script type="text/javascript" src="{{ asset('js/scroll.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/multiple-slider3.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/filter-div.js') }}"></script>

    <script>
        $(document).ready(function() {
            $('#table-users').DataTable();
        } );

        /* Projects JS */
        $(".hover").mouseleave(
            function () {
            $(this).removeClass("hover");
            }
        );
    </script>

    @yield('js-after')


</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        @livewireStyles

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-dropdown')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
            {{-- <main class="py-4">
                @yield('content')
            </main> --}}
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/breadcrumb.blade.php
<!-- Breadcrumb -->
<nav aria-label="breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            @yield('breadcrumb')
        </ol>
    </div>
</nav>

resources/views/layouts/filter-div.blade.php
<div class="col-lg-12 text-center text-black">
    <h2 id="text1" class="section-heading content-center text-uppercase">Desarrollo de Aplicaciones
        Web<span>&#160;</span></h2>
    <h3 class="section-subheading text-muted"></h3>
    <h2>Filter DIV Elements</h2>

    <div id="filter-container">
        <button class="btn-f active" onclick="filterSelection('all')"> Todos</button>
        <button class="btn-f" onclick="filterSelection('cars')"> Cars</button>
        <button class="btn-f" onclick="filterSelection('animals')"> Animals</button>
        <button class="btn-f" onclick="filterSelection('fruits')"> Fruits</button>
        <button class="btn-f" onclick="filterSelection('colors')"> Colors</button>
    </div>

    <div class="container-a contect-center">
        <div class="filterDiv cars">BMW</div>
        <div class="filterDiv colors fruits">Orange</div>
        <div class="filterDiv cars">Volvo</div>
        <div class="filterDiv colors">Red</div>
        <div class="filterDiv cars animals">Mustang</div>
        <div class="filterDiv colors">Blue</div>
        <div class="filterDiv animals">Cat</div>
        <div class="filterDiv animals">Dog</div>
        <div class="filterDiv fruits">Melon</div>
        <div class="filterDiv fruits animals">Kiwi</div>
        <div class="filterDiv fruits">Banana</div>
        <div class="filterDiv fruits">Lemon</div>
        <div class="filterDiv animals">Cow</div>
    </div>
</div>

resources/views/layouts/footer.blade.php
<!-- Footer -->
<footer class="footer">
    <div class="footer-middle">
        <div class="container">
            <div class="row pb-2">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-pad text-center">
                        <address>
                            <h4 class="h4">PARADOX WEB</h4>
                            <span class="oi oi-location"></span> Figueres, GI 17600<br />
                            <abbr title="Phone"></abbr><span class="oi oi-phone"></span> +34 697321944<br>
                            <span class="oi oi-envelope-closed"></span><a href="mailto:info@paradox-web.com"> info@paradox-web.com</a>
                        </address>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="footer-pad text-center">
                        <h4 class="h4">Heading 1</h4>
                        <ul class="list-unstyled">
                            <li><a href="#!">Información</a></li>
                            <li><a href="#!">Aviso Legal</a></li>
                            <li><a href="#!">Contacto</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="footer-pad text-center">
                        <h4 class="h4">Heading 2</h4>
                        <ul class="list-unstyled">
                            <li><a href="#!">Link 1</a></li>
                            <li><a href="#!">Link 2</a></li>
                            <li><a href="#!">Link 3</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3  col-sm-6 text-center" style="padding-bottom: 10px;">
                    <h4 class="h4">Follow Us</h4>
                    <a href="#">
                        <i class="fab fa-twitter fa-lg"></i>
                    </a>&nbsp;
                    <a href="#">
                        <i class="fab fa-facebook fa-lg"></i>
                    </a>&nbsp;
                    <a href="#">
                        <i class="fab fa-instagram fa-lg"></i>
                    </a>&nbsp;
                    <a href="#">
                        <i class="fab fa-linkedin fa-lg"></i>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 copy">
                    <p class="text-center">&copy; Copyright 2021 - <a href="https://paradox-web.com">
                        paradox-web.com</a> All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button-->
<a onclick="topFunction()" id="btnToTop" title="Go to top"><i class="fas fa-angle-up"></i></a>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.js" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/jumbotron.blade.php
<!-- Jumbotron -->
<div class="jumbotron jumbotron-fluid" style="background-image:linear-gradient(to right, #fed136 , #fa944b00),url('images/pages/programmer.jpg');">
    <div class="container">
        <h1 class="display-4 paradox">PARADOX WEB</h1>
        <p class="lead">Paradox Web es una empresa especializada en ofrecer soluciones creativas, tecnológicas y funcionales para cualquier tipo de servicios y aplicaciones online, siempre enfocadas a Internet.</p>
    </div>
</div>

resources/views/layouts/mini-slider.blade.php
<!-- Bootstrap 4 Multiple Item Carousel - Advances all 4 slides each time https://www.codeply.com/go/HDu8lT7NxJ -->
<!-- ... -->
<!-- Bootstrap 4 Multiple Item Carousel - Advances one slide at a time https://www.codeply.com/go/3EQkUOhhZz -->
<!-- Configurations: multiple-slider3.css i multiple-slider3.js-->
<div id="recipeCarousel" class="carousel slide w-100" data-ride="carousel">
    <div class="carousel-inner w-100" role="listbox">
        <div class="carousel-item active">
            <img class="d-block col-lg-3 col-md-4 col-sm-6 col-12 img-fluid" src="images/mini-slider/1.jpg">
        </div>
        <div class="carousel-item">
            <img class="d-block col-lg-3 col-md-4 col-sm-6 col-12 img-fluid" src="images/mini-slider/2.jpg">
        </div>
        <div class="carousel-item">
            <img class="d-block col-lg-3 col-md-4 col-sm-6 col-12 img-fluid" src="images/mini-slider/3.jpg">
        </div>
        <div class="carousel-item">
            <img class="d-block col-lg-3 col-md-4 col-sm-6 col-12 img-fluid" src="images/mini-slider/4.jpg">
        </div>
        <div class="carousel-item">
            <img class="d-block col-lg-3 col-md-4 col-sm-6 col-12 img-fluid" src="images/mini-slider/5.jpg">
        </div>
        <div class="carousel-item">
            <img class="d-block col-lg-3 col-md-4 col-sm-6 col-12 img-fluid" src="images/mini-slider/6.jpg">
        </div>
        <div class="carousel-item">
            <img class="d-block col-lg-3 col-md-4 col-sm-6 col-12 img-fluid" src="images/mini-slider/7.jpg">
        </div>
    </div>
    <a class="carousel-control-prev" href="#recipeCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#recipeCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

resources/views/layouts/nav-admin.blade.php
{{-- <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm"> --}}
<nav class="navbar navbar-expand-lg navbar-dark shadow-sm bg-secondary">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {{-- Con la ayuda de setActive en app/helpers.php --}}
                <li class="nav-item {{ setNavActive('courses.*') }}">
                    <a class="nav-link text-center" href="{{ route('courses.index') }}">
                        <i class="fas fa-school"></i><br><span>@lang('Schools')</span>
                    </a>
                </li>
                <li class="nav-item {{ setNavActive('courses.*') }}">
                    <a class="nav-link text-center" href="{{ route('courses.index') }}">
                        <i class="fas fa-chalkboard-teacher"></i><br><span>@lang('Teachers')</span>
                    </a>
                </li>
                <li class="nav-item {{ setNavActive('courses.*') }}">
                    <a class="nav-link text-center" href="{{ route('courses.index') }}">
                        <i class="fas fa-graduation-cap"></i><br><span>@lang('Certificates')</span>
                    </a>
                </li>
                <li class="nav-item {{ setNavActive('courses.*') }}">
                    <a class="nav-link text-center" href="{{ route('courses.index') }}">
                        <i class="fas fa-certificate"></i><br><span>@lang('Certificates')</span>
                    </a>
                </li>
                <li class="nav-item {{ setNavActive('courses.*') }}">
                    <a class="nav-link text-center" href="{{ route('courses.index') }}">
                        <i class="fab fa-leanpub"></i><br><span>@lang('Courses')</span>
                    </a>
                </li>
                <li class="nav-item {{ setNavActive('messages.*') }}">
                    <a class="nav-link text-center" href="{{ route('messages.index') }}">
                        <i class="far fa-comment-alt"></i><br><span>@lang('Messages')</span>
                    </a>
                </li>
                <li class="nav-item {{ setNavActive('users.*') }}">
                    <a class="nav-link text-center" href="{{ route('users.index') }}">
                        <i class="fas fa-users"></i><br><span>@lang('Users')</span>
                    </a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"> </li>
            </ul>

        </div>
    </div>
</nav>

resources/views/layouts/nav.blade.php
{{-- <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm"> --}}
<nav id="page-top" class="navbar navbar-expand-lg navbar-dark shadow-sm bg-light nav-style">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            <img src="images/pages/chicken.gif" class="d-inline-block align-top" style="width: auto;height:30px">
        </a>
        <a class="navbar-brand d-flex align-items-center" href="{{ url('/') }}">
            <span class="pt-2 paradox">PARADOX WEB</span>
        </a>
        {{-- <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a> --}}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

                {{-- Alternativa larga de navegación --}}
                {{-- <li class="nav-item {{ request()->routeIs('home') ? 'active' : ''}}"> --}}

                {{-- Hay 2  Maneras de llamar al traductor
                @lang('Home')
                {{ __('Home') }} --}}

                {{-- Con la ayuda de setActive en app/helpers.php --}}
                <li class="nav-item {{ setNavActive('home') }}">
                    <a class="nav-link" href="{{ route('home') }}">@lang('Home')</a>
                </li>
                <li class="nav-item {{ setNavActive('about') }}">
                    <a class="nav-link" href="{{ route('about') }}">@lang('About')</a>
                </li>
                <li class="nav-item {{ setNavActive('courses.*') }}">
                    <a class="nav-link" href="{{ route('courses.index') }}">@lang('Courses')</a>
                </li>
                @if (auth()->check())
                    <li class="nav-item {{ setNavActive('messages.*') }}">
                        <a class="nav-link" href="{{ route('messages.index') }}">@lang('Messages')</a>
                    </li>
                    {{-- @if (auth()->user()->role === 'admin') --}}
                    @if (auth()->user()->hasRoles(['super-admin','admin']))

                        <li class="nav-item {{ setNavActive('users.*') }}">
                            <a class="nav-link" href="{{ route('users.index') }}">@lang('Users')</a>
                        </li>
                    @endif
                @endif
                <li class="nav-item {{ setNavActive('contact') }}">
                    <a class="nav-link" href="{{ route('contact') }}">@lang('Contact')</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link" id="langSelect" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if ( Config::get('app.locale') == 'en')
                            <span class="flag-icon flag-icon-gb"></span>
                        @elseif ( Config::get('app.locale') == 'es' )
                            <span class="flag-icon flag-icon-es"></span>
                        @elseif ( Config::get('app.locale') == 'ca' )
                            <span class="flag-icon flag-icon-es-ca"></span>
                        @endif
                    </a>
                    <div class="dropdown-menu" aria-labelledby="langSelect">
                        <a class="dropdown-item" href="{{ route('language','es') }}">
                            <span class="flag-icon flag-icon-es"></span> ES
                        </a>
                        <a class="dropdown-item" href="{{ route('language','ca') }}">
                            <span class="flag-icon flag-icon-es-ca"></span> CA
                        </a>
                        <a class="dropdown-item" href="{{ route('language','en') }}">
                            <span class="flag-icon flag-icon-gb"></span> EN
                        </a>
                    </div>
                </li>
                <!-- Button modal menu -->
                <li class="nav-item">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalMenu">Menu</button>
                </li>
                {{-- <li class="nav-item dropdown">
                    <a class="nav-link" id="dropdownMessages" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="far fa-bell fa-lg"></i><small class="badge badge-pill badge-danger align-top">9</small>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMessages">
                        <button class="dropdown-item" type="button">Action</button>
                        <button class="dropdown-item" type="button">Another action</button>
                        <button class="dropdown-item" type="button">Something else here</button>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fas fa-moon fa-lg"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fas fa-adjust fa-lg"></i></a>
                </li> --}}

                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else

                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>

        </div>
    </div>
</nav>